# Generated by Django 4.2.5 on 2023-09-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberGuess', '0002_gamesession_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='secret_number',
            field=models.IntegerField(null=True),
        ),
    ]
